// Plain-English definitions of every term the course introduces, with the chapter that builds it.
export const GLOSSARY = [
  { term: 'Token', def: 'A symbol the model reads or writes, stored as a number. Here: one of 26 letters, plus the start/end symbol. Big models use word pieces.', ch: 1 },
  { term: 'BOS (start/end symbol)', def: 'A special extra symbol that marks "a name begins here" and "a name ends here". Always the last number in the alphabet (26 here).', ch: 1 },
  { term: 'Vocabulary', def: 'The full list of symbols the model knows, with their numbers. 27 here.', ch: 1 },
  { term: 'Probability', def: 'How likely something is, as a number from 0 (never) to 1 (always). All the options together add up to 1.', ch: 2 },
  { term: 'Sampling', def: 'Choosing an option at random, where each option\'s chance is its probability. Like spinning a weighted wheel.', ch: 2 },
  { term: 'Bigram', def: 'A pair of neighbouring symbols. A bigram model predicts the next symbol from only the one before it.', ch: 2 },
  { term: 'Context', def: 'Everything the model is allowed to look at when predicting the next symbol.', ch: 2 },
  { term: 'Surprise (−log p)', def: 'How shocked the model is by what really happened: small when it gave the right answer a high probability, huge when it gave it almost none.', ch: 3 },
  { term: 'Logarithm', def: 'The answer to "how many times did I multiply by 10 (or by e) to get here?". It turns multiplying into adding, and turns tiny probabilities into manageable numbers.', ch: 3 },
  { term: 'Loss', def: 'The model\'s average surprise over many examples. One number for how bad it is; lower is better. Pure chance on 27 symbols scores 3.30.', ch: 3 },
  { term: 'Parameter (dial)', def: 'A number inside the model that training is allowed to change. microgpt has 4,064.', ch: 4 },
  { term: 'Training', def: 'Repeatedly turning the dials in the direction that lowers the loss.', ch: 4 },
  { term: 'Slope (gradient)', def: 'How much the loss changes if you nudge one dial up a tiny bit. It tells you which way to turn it, and how strongly.', ch: 5 },
  { term: 'Gradient descent', def: 'Nudge every dial a small step against its slope, then repeat. Like walking downhill in fog by feeling the ground at your feet.', ch: 5 },
  { term: 'Learning rate', def: 'How big each step is. Too small and training crawls; too big and it overshoots and bounces.', ch: 5 },
  { term: 'Derivative', def: 'The mathematical name for a slope: the rate at which something changes.', ch: 5 },
  { term: 'Chain rule', def: 'If A changes B and B changes C, then the slope of C with respect to A is the two slopes multiplied.', ch: 6 },
  { term: 'Local gradient', def: 'The slope of one single operation\'s output with respect to one of its inputs. The chain rule multiplies these along the way.', ch: 6 },
  { term: 'Backpropagation', def: 'Working backwards from the loss, applying the chain rule at each step, to get every dial\'s slope in one sweep.', ch: 7 },
  { term: 'Autograd', def: 'A system where numbers remember how they were made, so slopes can be found automatically. The Value class.', ch: 7 },
  { term: 'Class / object', def: 'A recipe for bundling data and abilities together (class), and one thing made from it (object). A Value object holds a number, its slope and its history.', ch: 7 },
  { term: 'Topological order', def: 'A line-up of the calculation where every number comes after the numbers it was made from. Backward goes through it in reverse.', ch: 7 },
  { term: 'Logits (scores)', def: 'The raw numbers a model outputs for each option before they are turned into probabilities. Can be negative or huge.', ch: 8 },
  { term: 'exp', def: 'The "grows by multiplying" function: always positive, and adding to the input multiplies the output. Used to turn any score into a positive weight.', ch: 8 },
  { term: 'Softmax', def: 'Turn scores into probabilities: take exp of each, then divide each by the total. Only the gaps between scores matter.', ch: 8 },
  { term: 'Embedding', def: 'A learned list of numbers (coordinates) standing for a symbol, so that similar symbols can end up close together.', ch: 9 },
  { term: 'Dot product', def: 'Multiply two lists of numbers pairwise and add them up. A score for how well they line up.', ch: 9 },
  { term: 'Linear layer', def: 'A bank of dot products: each output is the input dotted with one row of dials. Written linear(x, w).', ch: 9 },
  { term: 'Matrix', def: 'A grid of numbers. Here, a list of rows, each row being one set of dials.', ch: 9 },
  { term: 'Attention', def: 'Letting each position look back at earlier positions and blend in the information from the ones that matter most.', ch: 10 },
  { term: 'Query, key, value', def: 'Each position asks a question (query), advertises what it holds (key), and offers its content (value). Matching query to key decides how much of each value to take.', ch: 10 },
  { term: 'Attention head', def: 'One independent attention process, working in its own slice of the numbers. microgpt has four.', ch: 11 },
  { term: 'MLP', def: 'A small think-it-over network applied to each position separately: expand, gate with ReLU, shrink.', ch: 12 },
  { term: 'ReLU', def: 'Keep positive numbers, turn negatives into zero. The bend that stops stacked layers collapsing into one.', ch: 12 },
  { term: 'Non-linearity', def: 'Any step that isn\'t just scaling and adding. Without one, any number of layers is equivalent to a single layer.', ch: 12 },
  { term: 'Residual (skip) connection', def: 'Adding a layer\'s input back to its output, so the original signal and its slopes always have a direct route through.', ch: 13 },
  { term: 'RMSNorm', def: 'Rescale a list of numbers so its typical size is 1, keeping the signal from shrinking or exploding as it passes through layers.', ch: 13 },
  { term: 'Transformer', def: 'The architecture of attention blocks and MLP blocks, joined by skip lanes and normalisation. What gpt() is.', ch: 14 },
  { term: 'Context window (block size)', def: 'How many positions the model can look at in one go. 8 here.', ch: 14 },
  { term: 'Momentum', def: 'Keeping a running average of recent slopes, so noise cancels and a steady direction builds.', ch: 15 },
  { term: 'Adam', def: 'An optimiser that gives each dial its own step size (from a running average of its squared slope) and uses momentum.', ch: 15 },
  { term: 'Learning-rate decay', def: 'Shrinking the learning rate as training goes on, big steps first, careful steps at the end. Here a cosine curve.', ch: 15 },
  { term: 'Step', def: 'One trip round the training loop: pick a name, measure the loss, find slopes, move the dials.', ch: 16 },
  { term: 'Teacher forcing', def: 'Always showing the model the true history while it learns, never its own guesses.', ch: 16 },
  { term: 'Temperature', def: 'A number the scores are divided by before softmax. Low is safe and repetitive; high is varied and eventually nonsense.', ch: 17 },
  { term: 'Hallucination', def: 'A fluent answer that isn\'t true. A model is trained to be plausible, not checked, so it can sound right with no evidence behind it.', ch: 17 },
  { term: 'Inference', def: 'Using a trained model to produce output, as opposed to training it.', ch: 17 },
  { term: 'Generalisation', def: 'Doing well on examples the model has never seen, because it learned habits and not a list.', ch: 17 },
  { term: 'Byte-pair encoding (BPE)', def: 'A way to build a vocabulary of word pieces by repeatedly merging the most common neighbouring pairs. How big models tokenise.', ch: 19 },
];
