// Plain-English recipes for every exercise. Each `lines` entry is one step of the real program:
//   en     what the step means, in everyday words
//   py     the actual Python line (shown beside the step, and what really runs)
//   depth  how far the line is indented (indentation = "inside the thing above")
// A step with `blank: true` is the learner's job: they pick the right plain-English option from `options`
// (`answer` is the index of the correct one; `why[i]` explains a tempting wrong one).
// Joining the `py` lines gives a program that passes the same hidden check as the Python editor.

export const PLAIN = {
  'ch1-load': {
    intro: 'This recipe reads the names file into a list. Nothing to fill in. Press run and watch.',
    lines: [
      { en: 'Make a list called docs. For every line in the file: tidy up stray spaces, and skip any line that turns out empty.', py: "docs = [l.strip() for l in open('input.txt').read().strip().split('\\n') if l.strip()]" },
      { en: 'Say how many names we ended up with.', py: "print(len(docs), 'names')" },
      { en: 'Show the first five of them.', py: 'print(docs[:5])' },
    ],
  },

  'ch1-vocab': {
    lines: [
      {
        blank: true, depth: 0,
        ask: 'We need the list of every distinct letter used in the names, in alphabetical order. Which plan does that?',
        options: [
          'Take just the first name and sort its letters',
          'Glue all the names into one long string, throw away repeated letters, then sort what is left',
          'Count how many names there are',
          'Sort the names alphabetically',
        ],
        answer: 1,
        why: { 0: 'One name only has a few letters. We want every letter that appears anywhere.', 2: 'That gives us a count, not a list of letters.', 3: 'That sorts the names, but we want the individual letters.' },
        en: 'Glue all the names into one long string, throw away repeated letters, then sort what is left. Call the result uchars.',
        py: "uchars = sorted(set(''.join(docs)))",
      },
      {
        blank: true, depth: 0,
        ask: 'The 26 letters take the numbers 0 to 25. What number should the special start/end symbol (BOS) get?',
        options: ['0, because it comes first', 'The next free number: however many letters there are (26)', '-1, so it stands out', 'The number of names in the file'],
        answer: 1,
        why: { 0: 'The number 0 already belongs to the letter a.', 2: 'It would work, but a negative position confuses a list. We simply continue counting.', 3: 'That number would be huge and has nothing to do with the alphabet.' },
        en: 'Give the start/end symbol the next free number, which is the count of letters.',
        py: 'BOS = len(uchars)',
      },
      { en: 'Show the alphabet.', py: 'print(uchars)' },
      { en: 'Show the number for BOS.', py: "print('BOS =', BOS)" },
    ],
  },

  'ch1-encode': {
    lines: [
      { en: 'Define a recipe called encode. You hand it a name.', py: 'def encode(doc):', depth: 0 },
      {
        blank: true, depth: 1,
        ask: 'What should encode hand back for the name "emma"?',
        options: [
          'Just the number of each letter',
          'The letters themselves, unchanged',
          'The start symbol, then the number of each letter, then the start/end symbol again',
          'How many letters the name has',
        ],
        answer: 2,
        why: { 0: 'Close, but the model also needs to know where the name starts and ends. Wrap it.', 1: 'The point is to turn letters into numbers.', 3: 'A count loses the letters entirely.' },
        en: 'Hand back: the start symbol, then each letter swapped for its number, then the start/end symbol again.',
        py: 'return [BOS] + [uchars.index(ch) for ch in doc] + [BOS]',
      },
      { en: 'Try it on "emma".', py: "print(encode('emma'))", depth: 0 },
    ],
  },

  'ch1-babble': {
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: 'Define a recipe called babble that makes one random "name".', py: 'def babble():' },
      { en: 'Start with an empty name.', py: "name = ''", depth: 1 },
      { en: 'Keep repeating the next steps until we say stop.', py: 'while True:', depth: 1 },
      { en: 'Roll a 27-sided die: every symbol equally likely.', py: 't = random.randrange(len(uchars) + 1)', depth: 2 },
      { en: 'If the die shows the start/end symbol...', py: 'if t == BOS:', depth: 2 },
      { en: '...stop repeating.', py: 'break', depth: 3 },
      {
        blank: true, depth: 2,
        ask: 'Otherwise (the die showed a letter), what do we do with the roll?',
        options: ['Write down the number itself', 'Write down the letter that has that number', 'Throw the name away and start over', 'Stop repeating'],
        answer: 1,
        why: { 0: 'A name made of numbers is not a name. We need the letter that goes with that number.', 2: 'Then we would never finish a name.', 3: 'We only stop when the die shows the start/end symbol.' },
        en: 'Add the letter with that number to the end of the name.',
        py: 'name += uchars[t]',
      },
      { en: 'Hand back the finished name.', py: 'return name', depth: 1 },
      { en: 'Do the next two steps 8 times.', py: 'for _ in range(8):' },
      { en: 'Make a name and show it.', py: 'print(babble())', depth: 1 },
      { en: 'Make 2,000 names and report their average length.', py: "print('average length:', sum(len(babble()) for _ in range(2000)) / 2000)" },
    ],
  },

  'ch1-seed': {
    intro: 'Nothing to fill in. Run it, then compare the two rows of numbers.',
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: 'Set the dice to starting position 42.', py: 'random.seed(42)' },
      { en: 'Roll 6 dice (each 0 to 26) and show them.', py: 'print([random.randrange(27) for _ in range(6)])' },
      { en: 'Rewind the dice to starting position 42 again.', py: 'random.seed(42)' },
      { en: 'Roll 6 again. Do they fall the same way?', py: 'print([random.randrange(27) for _ in range(6)])' },
    ],
  },

  'ch2-count': {
    lines: [
      { en: 'Make a tally sheet: one tally per letter, every tally starting at zero.', py: 'counts = {ch: 0 for ch in uchars}' },
      { en: 'Go through every name...', py: 'for doc in docs:' },
      { en: '...and every letter in that name.', py: 'for ch in doc:', depth: 1 },
      {
        blank: true, depth: 2,
        ask: 'For each letter we meet, what should happen to the tally sheet?',
        options: [
          "Reset that letter's tally to zero",
          "Add 1 to that letter's tally",
          "Add the name's length to the tally",
          'Add 1 to every letter’s tally',
        ],
        answer: 1,
        why: { 0: 'Then every tally would end up as zero or one. We want a running total.', 2: 'That would count how long names are, not how often each letter appears.', 3: 'Then all tallies would be identical, so we would learn nothing about which letters are common.' },
        en: "Add 1 to that letter's tally.",
        py: 'counts[ch] += 1',
      },
      { en: 'Show the tallies for a, e and q.', py: "print('a:', counts['a'], '  e:', counts['e'], '  q:', counts['q'])" },
    ],
  },

  'ch2-choices': {
    intro: 'Nothing to fill in. Run it a few times and watch the letters that come out.',
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: "Make a list of weights: each letter's tally. Bigger tally means a bigger wedge on the wheel.", py: 'weights = [counts[ch] for ch in uchars]' },
      { en: 'Spin the wheel 12 times, and show the letters it lands on.', py: 'print(random.choices(uchars, weights=weights, k=12))' },
    ],
  },

  'ch2-table': {
    lines: [
      { en: 'There are 27 symbols in all: 26 letters plus the start/end symbol.', py: 'V = len(uchars) + 1' },
      { en: 'Make a 27 by 27 grid of zeros. Row = the symbol just written, column = the symbol that came next.', py: 'table = [[0] * V for _ in range(V)]' },
      { en: 'Go through every name...', py: 'for doc in docs:' },
      { en: '...turn it into numbers, wrapped in start/end symbols...', py: 'tokens = [BOS] + [uchars.index(ch) for ch in doc] + [BOS]', depth: 1 },
      { en: '...and look at every neighbouring pair: a symbol (prev) and the one right after it (nxt).', py: 'for prev, nxt in zip(tokens, tokens[1:]):', depth: 1 },
      {
        blank: true, depth: 2,
        ask: 'For each pair, what do we record in the grid?',
        options: [
          'Add 1 to the cell in row prev, column nxt',
          'Add 1 to the whole row prev',
          'Set that cell to 1',
          'Add 1 to the cell in row nxt, column prev (the other way round)',
        ],
        answer: 0,
        why: { 1: 'That only counts how often prev appeared. We want to know which symbol FOLLOWED it.', 2: 'Then a pair seen 500 times would look the same as a pair seen once. We need running totals.', 3: 'Careful: that records "nxt followed by prev", which is the reverse of what happened.' },
        en: 'Add 1 to the cell in row prev, column nxt.',
        py: 'table[prev][nxt] += 1',
      },
      { en: 'Show how many names start with a.', py: "print('names that start with a:', table[BOS][0])" },
      { en: "Show how often q is followed by u.", py: "print(\"'q' is followed by 'u' this many times:\", table[uchars.index('q')][uchars.index('u')])" },
    ],
  },

  'ch2-make': {
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: 'Define a recipe called make_name.', py: 'def make_name():' },
      { en: 'Start from the start symbol.', py: 'tok = BOS', depth: 1 },
      { en: 'Start with an empty name.', py: "name = ''", depth: 1 },
      { en: 'Keep repeating the next steps until we say stop.', py: 'while True:', depth: 1 },
      { en: "Spin the wheel for the last symbol's row. Wherever it lands is the next symbol.", py: 'tok = random.choices(range(V), weights=table[tok])[0]', depth: 2 },
      { en: 'If the wheel landed on the start/end symbol...', py: 'if tok == BOS:', depth: 2 },
      {
        blank: true, depth: 3,
        ask: '...what should happen?',
        options: ['Add it to the name anyway', 'Spin again', 'Stop repeating: the name is finished', 'Start the name over'],
        answer: 2,
        why: { 0: 'The start/end symbol is not a letter. Python would crash trying to look up a letter for it.', 1: 'Then the name would never end.', 3: 'We would throw away a perfectly good name.' },
        en: 'Stop repeating: the name is finished.',
        py: 'break',
      },
      { en: 'Otherwise it was a letter, so add it to the name.', py: 'name += uchars[tok]', depth: 2 },
      { en: 'Hand back the finished name.', py: 'return name', depth: 1 },
      { en: 'Make 10 names and show them.', py: 'for _ in range(10):' },
      { en: 'Make one name and show it.', py: 'print(make_name())', depth: 1 },
    ],
  },

  'ch3-surprise': {
    lines: [
      { en: 'Borrow the maths toolkit (it has logarithms).', py: 'import math' },
      { en: 'Define a recipe called surprise. You hand it a probability p.', py: 'def surprise(p):' },
      {
        blank: true, depth: 1,
        ask: 'How surprised should we be by something with probability p?',
        options: [
          'The logarithm of p',
          'Minus the logarithm of p',
          'p multiplied by itself',
          '1 divided by p',
        ],
        answer: 1,
        why: { 0: 'Close! But the log of a small probability is a big negative number, so rarer events would score LOWER. Flip the sign.', 2: 'That makes rare things less surprising, which is backwards.', 3: 'It points the right way, but it would not turn multiplying into adding, which is the whole reason for using logs.' },
        en: 'Hand back minus the logarithm of p.',
        py: 'return -math.log(p)',
      },
      { en: 'For each of these probabilities...', py: 'for p in [0.99, 0.5, 0.1, 1/27, 0.01, 0.001]:' },
      { en: '...show the probability and how surprising it is.', py: 'print(f"p = {p:<8.4f}  surprise = {surprise(p):.3f}")', depth: 1 },
    ],
  },

  'ch3-loss': {
    lines: [
      { en: 'Define a recipe called name_loss. You hand it a name.', py: 'def name_loss(name):' },
      { en: 'Turn the name into numbers, wrapped in start/end symbols.', py: 'tokens = [BOS] + [uchars.index(ch) for ch in name] + [BOS]', depth: 1 },
      { en: 'Start an empty list of surprise scores.', py: 'losses = []', depth: 1 },
      { en: 'Look at every neighbouring pair of symbols.', py: 'for prev, nxt in zip(tokens, tokens[1:]):', depth: 1 },
      { en: 'Ask the table how likely that step was.', py: 'p = P(prev, nxt)', depth: 2 },
      {
        blank: true, depth: 2,
        ask: 'What should we store for this step?',
        options: [
          'p itself',
          'How surprised the table was: minus the log of p',
          'The log of p, with no minus sign',
          '1 minus p',
        ],
        answer: 1,
        why: { 0: 'That is the probability, not the surprise. We built surprise precisely so tiny probabilities do not take over.', 2: 'All our scores would come out negative, and "bigger is worse" would be backwards.', 3: 'This gets smaller as p gets bigger, which sort of works, but it is not surprise and does not turn multiplying into adding.' },
        en: 'Add the surprise (minus the log of p) to the list.',
        py: 'losses.append(-math.log(p))',
      },
      { en: 'Hand back the average: add the scores up, divide by how many there are.', py: 'return sum(losses) / len(losses)', depth: 1 },
      { en: 'Score three names.', py: "for n in ['emma', 'olivia', 'mia']:" },
      { en: 'Show each name with its score.', py: 'print(n, round(name_loss(n), 3))', depth: 1 },
    ],
  },

  'ch3-break': {
    intro: 'Nothing to fill in. This one is meant to crash. Run it and read the error.',
    lines: [
      { en: "Ask the table: how likely is 'q' right after 'x'? (Spoiler: no name has ever had that.)", py: "print(P(uchars.index('x'), uchars.index('q')))" },
      { en: 'Now score a name that contains that pair.', py: "print(name_loss('xqzvb'))" },
    ],
  },

  'ch4-climb': {
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: 'Start with both dials in the middle (50%).', py: 'a, b = 0.5, 0.5' },
      { en: 'Measure the loss with the dials where they are now.', py: 'best = loss(a, b)' },
      { en: 'Repeat the next steps 500 times.', py: 'for attempt in range(500):' },
      { en: 'Make a trial setting for dial A: nudge it by a small random amount.', py: 'a2 = a + random.gauss(0, 0.05)', depth: 1 },
      { en: 'Make a trial setting for dial B the same way.', py: 'b2 = b + random.gauss(0, 0.05)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'When should we adopt the trial setting?',
        options: [
          'Only if it gives a lower loss than what we have',
          'Only if it gives a higher loss than what we have',
          'Every time, whatever the loss',
          'Only if dial A went up',
        ],
        answer: 0,
        why: { 1: 'That would make the model worse and worse. We are trying to push the loss DOWN.', 2: 'Then the dials would just wander randomly and never settle anywhere good.', 3: 'Whether a dial went up or down is irrelevant. What matters is what happened to the loss.' },
        en: 'Only adopt the trial setting if it gives a lower loss.',
        py: 'if loss(a2, b2) < best:',
      },
      { en: 'Adopt it: move the dials there, and remember the new loss.', py: 'a, b, best = a2, b2, loss(a2, b2)', depth: 2 },
      { en: 'Show where the dials ended up, and the loss.', py: "print('dials:', round(a, 3), round(b, 3), ' loss:', round(best, 4))" },
    ],
  },

  'ch5-slope': {
    lines: [
      { en: 'Define a recipe called slope. You hand it a function f, a spot x, and a tiny wiggle h (we default h to 0.0001).', py: 'def slope(f, x, h=0.0001):' },
      {
        blank: true, depth: 1,
        ask: 'How do we measure how steeply f is changing at x?',
        options: [
          'Nudge x up by h, see how much f changed, and divide that change by h',
          'Nudge x up by h and report how much f changed (no dividing)',
          'Nudge x up by h and report the change the other way round: f(x) minus f(x + h), divided by h',
          'Divide f(x) by h',
        ],
        answer: 0,
        why: { 1: 'Without dividing by h, the answer depends on how big the wiggle was. A smaller wiggle would give a smaller "slope" for the same hill.', 2: 'That has the sign flipped: a rising function would report a negative slope.', 3: 'That does not involve the change in f at all.' },
        en: 'Nudge x up by h, see how much f changed, and divide that change by h.',
        py: 'return (f(x + h) - f(x)) / h',
      },
      { en: 'Try it on x times x at x = 3. (The exact answer is 6.)', py: 'print(slope(lambda x: x * x, 3))' },
      { en: 'Try it on a straight line that rises 5 for every 1 across. The slope should be 5.', py: 'print(slope(lambda x: 5 * x, 10))' },
    ],
  },

  'ch5-descent': {
    lines: [
      { en: 'Start with both dials in the middle.', py: 'a, b = 0.5, 0.5' },
      { en: 'Set the learning rate: how big a step to take.', py: 'lr = 0.2' },
      { en: 'Repeat the next steps 40 times.', py: 'for step in range(40):' },
      { en: 'Choose a tiny wiggle.', py: 'h = 0.0001', depth: 1 },
      { en: 'Wiggle dial A and see what the loss does. That ratio is dial A\'s slope.', py: 'slope_a = (loss(a + h, b) - loss(a, b)) / h', depth: 1 },
      { en: 'Wiggle dial B the same way.', py: 'slope_b = (loss(a, b + h) - loss(a, b)) / h', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'How should dial A change?',
        options: [
          'Add (learning rate × slope): step uphill',
          'Subtract (learning rate × slope): step downhill',
          'Set it to the slope',
          'Multiply it by the slope',
        ],
        answer: 1,
        why: { 0: 'That climbs the hill. A positive slope means raising the dial RAISES the loss, so we must go the other way.', 2: 'The slope is a steepness, not a dial setting.', 3: 'That would shrink or grow the dial for no reason related to the loss.' },
        en: 'Subtract (learning rate × slope) from dial A: step downhill.',
        py: 'a = a - lr * slope_a',
      },
      { en: 'Do the same for dial B.', py: 'b = b - lr * slope_b', depth: 1 },
      { en: 'Show where the dials ended up, and the loss.', py: "print('dials:', round(a, 3), round(b, 3), ' loss:', round(loss(a, b), 4))" },
    ],
  },

  'ch6-backward': {
    lines: [
      { en: 'Define a recipe for an adding step, c = a + b. You hand it the upstream slope: how much the loss changes per unit change in c.', py: 'def add_backward(upstream):' },
      {
        blank: true, depth: 1,
        ask: 'If c = a + b, then raising a by 1 raises c by 1. So per unit change in a, how much does the loss change?',
        options: ['The same as the upstream slope', 'Zero: adding passes nothing back', 'Double the upstream slope', 'The value of b times the upstream slope'],
        answer: 0,
        why: { 1: 'Raising a does change c (by exactly 1), so some of the loss slope must flow back to a.', 2: 'Adding does not magnify anything. c moves by exactly as much as a does.', 3: 'That is the rule for multiplying, not adding.' },
        en: 'Dial a gets exactly the upstream slope.',
        py: 'grad_a = upstream',
      },
      { en: 'Dial b works the same way.', py: 'grad_b = upstream', depth: 1 },
      { en: 'Hand back both slopes.', py: 'return grad_a, grad_b', depth: 1 },
      { en: 'Define a recipe for a multiplying step, c = a × b.', py: 'def mul_backward(a, b, upstream):' },
      {
        blank: true, depth: 1,
        ask: 'If c = a × b, then raising a by 1 raises c by b. So per unit change in a, how much does the loss change?',
        options: ['a times the upstream slope', 'The upstream slope, unchanged', 'The other input, b, times the upstream slope', 'b plus the upstream slope'],
        answer: 2,
        why: { 0: 'That is the slope for b. Raising a changes c by b, not by a.', 1: 'That is the rule for adding. Multiplying scales the effect by the other input.', 3: 'Slopes multiply along a chain. They are never added to the upstream slope.' },
        en: 'Dial a gets the other input, b, times the upstream slope.',
        py: 'grad_a = b * upstream',
      },
      { en: 'Raising b by 1 raises c by a, so dial b gets a times the upstream slope.', py: 'grad_b = a * upstream', depth: 1 },
      { en: 'Hand back both slopes.', py: 'return grad_a, grad_b', depth: 1 },
      { en: 'Try it on our chain example: a = 2, b = 3, upstream slope 14. It should print (42, 28).', py: 'print(mul_backward(2, 3, 14))' },
    ],
  },

  'ch6-verify': {
    intro: 'Nothing to fill in. Run it: the slopes found by going backwards should match the wiggle test.',
    lines: [
      { en: 'Set the two inputs.', py: 'a, b = 2.0, 3.0' },
      { en: 'Forward pass, step 1: multiply.', py: 'c = a * b' },
      { en: 'Forward pass, step 2: add one.', py: 'd = c + 1' },
      { en: 'Forward pass, step 3: square it. That is the loss.', py: 'loss = d ** 2' },
      { en: 'Backward: the slope of d squared is 2d.', py: 'grad_d = 2 * d' },
      { en: 'Backward through the adding step.', py: 'grad_c, _ = add_backward(grad_d)' },
      { en: 'Backward through the multiplying step. Out come the slopes of a and b.', py: 'grad_a, grad_b = mul_backward(a, b, grad_c)' },
      { en: 'Show them.', py: "print('going backwards:', grad_a, grad_b)" },
      { en: 'Choose a tiny wiggle.', py: 'h = 1e-6' },
      { en: 'Check with the wiggle test: nudge each input and see what the loss does.', py: "print('wiggle test:    ', (((a + h) * b + 1) ** 2 - loss) / h, ((a * (b + h) + 1) ** 2 - loss) / h)" },
    ],
  },

  'ch7-cards': {
    lines: [
      { en: 'Define a recipe that makes a memory card. (The label is only a name we use later when drawing pictures.)', py: "def card(data, children=(), local_grads=(), label=''):" },
      { en: 'A card is a little record with four boxes: its value, its slope (starting at 0), the cards it was made from, and how sensitive it is to each of them.', py: "return {'data': data, 'grad': 0, 'children': children, 'local_grads': local_grads, 'label': label}", depth: 1 },
      { en: 'Define adding two cards.', py: 'def add(a, b):' },
      { en: "The new card's value is the sum. It remembers both ingredients, and each ingredient's local slope is 1.", py: "return card(a['data'] + b['data'], (a, b), (1, 1), '+')", depth: 1 },
      { en: 'Define multiplying two cards.', py: 'def mul(a, b):' },
      {
        blank: true, depth: 1,
        ask: 'The new card remembers its ingredients (a, b). What local slopes should it remember for them?',
        options: [
          "(1, 1): both just pass the slope straight through",
          "(a's value, b's value): each ingredient gets its own value",
          "(b's value, a's value): each ingredient gets the OTHER one's value",
          '(0, 0): multiplying hides the ingredients',
        ],
        answer: 2,
        why: { 0: 'That is the rule for adding. Multiplying scales the effect.', 1: 'Close, but swapped. Nudging a changes the product by b per unit, not by a.', 3: 'Then no slope could ever flow back through a multiplication.' },
        en: "Remember each ingredient's local slope as the OTHER ingredient's value.",
        py: "return card(a['data'] * b['data'], (a, b), (b['data'], a['data']), '×')",
      },
      { en: 'Try it: multiply the cards 2 and 3.', py: 'z = mul(card(2.0), card(3.0))' },
      { en: 'Show the value and the remembered local slopes. Expect 6.0 and (3.0, 2.0).', py: "print(z['data'], z['local_grads'])" },
    ],
  },

  'ch7-topo': {
    lines: [
      { en: 'Define a recipe that lines cards up so each comes after the cards it was made from.', py: 'def topo_order(root):' },
      { en: 'Start with an empty list, and an empty memory of the cards we have already seen.', py: 'order, seen = [], set()', depth: 1 },
      { en: 'Define a helper recipe called visit. It will call itself.', py: 'def visit(c):', depth: 1 },
      { en: 'If this card has not been seen yet...', py: 'if id(c) not in seen:', depth: 2 },
      { en: '...remember it (by its identity number), so we never process it twice.', py: 'seen.add(id(c))', depth: 3 },
      { en: 'Go through the cards it was made from...', py: "for parent in c['children']:", depth: 3 },
      { en: '...and visit each one first. Each of those may visit ITS ingredients, and so on.', py: 'visit(parent)', depth: 4 },
      {
        blank: true, depth: 3,
        ask: 'We are now back from visiting every ingredient of this card. What do we do with the card itself?',
        options: [
          'Mark it as seen (again)',
          'Add it to the list: all its ingredients are already on it',
          'Visit it again to double-check',
          'Throw it away',
        ],
        answer: 1,
        why: { 0: 'We did that earlier, before visiting the ingredients.', 2: 'It is already marked as seen, so that visit would do nothing.', 3: 'Then the list would stay empty.' },
        en: 'Add the card to the list now: everything it was made from is already there.',
        py: 'order.append(c)',
      },
      { en: 'Start the process at the final card (the loss).', py: 'visit(root)', depth: 1 },
      { en: 'Hand back the finished list.', py: 'return order', depth: 1 },
    ],
  },

  'ch7-backward': {
    lines: [
      { en: 'Define the backward sweep. You hand it the final card (the loss).', py: 'def backward(root):' },
      { en: 'Line the cards up, ingredients first.', py: 'order = topo_order(root)', depth: 1 },
      { en: 'The final card has slope 1 with respect to itself.', py: "root['grad'] = 1", depth: 1 },
      { en: 'Walk the list backwards: last card first.', py: 'for c in reversed(order):', depth: 1 },
      { en: 'For each ingredient of this card, together with its remembered local slope...', py: "for parent, local in zip(c['children'], c['local_grads']):", depth: 2 },
      {
        blank: true, depth: 3,
        ask: 'What should happen to the ingredient\'s slope?',
        options: [
          "Replace it with the local slope",
          "Add (local slope × this card's slope) to it",
          "Add just the local slope to it",
          "Multiply it by the local slope",
        ],
        answer: 1,
        why: { 0: 'That would forget slopes already received from other paths. A card used twice, such as a × a, needs both contributions added up.', 2: 'That ignores how much this card matters to the loss. Slopes must be chained: multiplied by the slope arriving from downstream.', 3: 'The slope arriving from downstream is what we must multiply the local slope by, and then we add the result in.' },
        en: "Add (local slope × this card's slope) to the ingredient's slope.",
        py: "parent['grad'] += local * c['grad']",
      },
    ],
  },

  'ch7-show': {
    intro: 'Nothing to fill in. Run it: your own engine builds the graph, and the page draws it.',
    lines: [
      { en: 'Make the two inputs as cards, with names for the picture.', py: "a, b = card(2.0, label='a'), card(3.0, label='b')" },
      { en: 'Multiply them.', py: 'c = mul(a, b)' },
      { en: 'Add 1.', py: 'd = add(c, card(1.0))' },
      { en: 'Square it. That is the loss.', py: 'loss = power(d, 2)' },
      { en: 'Run your backward sweep.', py: 'backward(loss)' },
      { en: 'Show the slopes it found for a and b.', py: "print('slopes:', a['grad'], b['grad'])" },
      { en: 'Draw the graph your code just built.', py: 'show(loss)' },
    ],
  },

  'ch7-train': {
    lines: [
      { en: 'Make the two dials as cards, both at 50%.', py: 'a, b = card(0.5), card(0.5)' },
      { en: 'Set the learning rate.', py: 'lr = 0.2' },
      { en: 'Repeat 40 times.', py: 'for step in range(40):' },
      { en: 'Forward: build a fresh graph of cards for the loss.', py: 'loss = vowel_loss(a, b)', depth: 1 },
      { en: "Forget last step's slopes on the two dial cards...", py: "a['grad'] = 0", depth: 1 },
      { en: '...(both of them).', py: "b['grad'] = 0", depth: 1 },
      { en: 'Backward: one sweep gives BOTH slopes.', py: 'backward(loss)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'How should dial A move?',
        options: [
          "Add (learning rate × its slope) to it",
          "Subtract (learning rate × its slope) from it",
          "Set it to its slope",
          "Leave it alone: only dial B needs to move",
        ],
        answer: 1,
        why: { 0: 'That climbs uphill. A positive slope means raising the dial raises the loss.', 2: 'A slope is a steepness, not a dial setting.', 3: 'Both dials have slopes and both should move.' },
        en: "Subtract (learning rate × its slope) from dial A's value.",
        py: "a['data'] = a['data'] - lr * a['grad']",
      },
      { en: 'Dial B moves the same way.', py: "b['data'] = b['data'] - lr * b['grad']", depth: 1 },
      { en: 'Show where the dials ended up, and the loss.', py: "print('dials:', round(a['data'], 3), round(b['data'], 3), ' loss:', round(vowel_loss(a, b)['data'], 4))" },
    ],
  },

  'ch7-break': {
    intro: 'Nothing to fill in. This version forgets to reset the slopes. Run it and watch what happens.',
    lines: [
      { en: 'Dials at 50%, learning rate 0.2.', py: 'a, b = card(0.5), card(0.5)' },
      { en: 'Learning rate.', py: 'lr = 0.2' },
      { en: 'Repeat 40 times.', py: 'for step in range(40):' },
      { en: 'Forward.', py: 'loss = vowel_loss(a, b)', depth: 1 },
      { en: 'Backward. We forgot to wipe the old slopes first!', py: 'backward(loss)', depth: 1 },
      { en: 'Move dial A.', py: "a['data'] = a['data'] - lr * a['grad']", depth: 1 },
      { en: 'Move dial B.', py: "b['data'] = b['data'] - lr * b['grad']", depth: 1 },
      { en: 'Show the dials after every step.', py: "print(step, round(a['data'], 3), round(b['data'], 3))", depth: 1 },
    ],
  },

  'ch7-class': {
    lines: [
      { en: 'Borrow the maths toolkit.', py: 'import math' },
      { en: 'Define a template for cards. Python calls it a class. Ours is named Value.', py: 'class Value:' },
      { en: 'How to fill in a brand-new card. (self means "the card being made".)', py: 'def __init__(self, data, children=(), local_grads=()):', depth: 1 },
      { en: 'Its value.', py: 'self.data = data', depth: 2 },
      { en: 'Its slope, starting at zero.', py: 'self.grad = 0', depth: 2 },
      { en: 'The cards it was made from.', py: 'self._children = children', depth: 2 },
      { en: 'How sensitive it is to each of them.', py: 'self._local_grads = local_grads', depth: 2 },
      { en: 'What to do when someone writes card + card.', py: 'def __add__(self, other):', depth: 1 },
      { en: 'If the other side is a plain number, wrap it in a card first.', py: 'other = other if isinstance(other, Value) else Value(other)', depth: 2 },
      { en: 'Make the sum card, remembering both ingredients and local slopes of 1.', py: 'return Value(self.data + other.data, (self, other), (1, 1))', depth: 2 },
      { en: 'What to do when someone writes card * card.', py: 'def __mul__(self, other):', depth: 1 },
      { en: 'Wrap a plain number first, as before.', py: 'other = other if isinstance(other, Value) else Value(other)', depth: 2 },
      {
        blank: true, depth: 2,
        ask: 'Make the product card. Which local slopes should it remember for (self, other)?',
        options: [
          '(1, 1)',
          '(self.data, other.data)',
          '(other.data, self.data): each gets the other one\'s value',
          '(0, 0)',
        ],
        answer: 2,
        why: { 0: 'That is the rule for adding.', 1: 'Swapped. Nudging self changes the product by other.data per unit.', 3: 'Slopes could never flow back through a multiplication.' },
        en: "Make the product card, remembering each side's local slope as the other side's value.",
        py: 'return Value(self.data * other.data, (self, other), (other.data, self.data))',
      },
      { en: 'What to do when someone writes card ** number.', py: 'def __pow__(self, other):', depth: 1 },
      { en: 'The local slope of x to the power k is k times x to the power k minus 1.', py: 'return Value(self.data ** other, (self,), (other * self.data ** (other - 1),))', depth: 2 },
      { en: 'The backward sweep, now a method of the card itself.', py: 'def backward(self):', depth: 1 },
      { en: 'Start with an empty list for the lined-up cards.', py: 'topo = []', depth: 2 },
      { en: 'And an empty memory of the cards we have seen.', py: 'visited = set()', depth: 2 },
      { en: 'The same self-calling helper as before, now with the cards themselves in the memory.', py: 'def build_topo(v):', depth: 2 },
      { en: 'If not seen yet...', py: 'if v not in visited:', depth: 3 },
      { en: '...remember it...', py: 'visited.add(v)', depth: 4 },
      { en: '...visit each ingredient first...', py: 'for child in v._children:', depth: 4 },
      { en: '...and visit it.', py: 'build_topo(child)', depth: 5 },
      { en: '...then add the card to the list.', py: 'topo.append(v)', depth: 4 },
      { en: 'Line everything up, starting from this card.', py: 'build_topo(self)', depth: 2 },
      { en: 'This card (the loss) has slope 1 with respect to itself.', py: 'self.grad = 1', depth: 2 },
      { en: 'Walk the list backwards.', py: 'for v in reversed(topo):', depth: 2 },
      { en: "For each ingredient and its local slope...", py: 'for child, local_grad in zip(v._children, v._local_grads):', depth: 3 },
      { en: "...add (local slope × this card's slope) to the ingredient's slope.", py: 'child.grad += local_grad * v.grad', depth: 4 },
      { en: 'Try it on the chain: (a × b + 1) squared.', py: 'a, b = Value(2.0), Value(3.0)' },
      { en: 'Notice how it reads like ordinary arithmetic now.', py: 'loss = (a * b + 1) ** 2' },
      { en: 'Run the backward sweep.', py: 'loss.backward()' },
      { en: 'Show the loss and the two slopes.', py: 'print(loss.data, a.grad, b.grad)' },
    ],
  },

  'ch8-softmax': {
    lines: [
      { en: "Borrow the maths toolkit (it has exp).", py: 'import math' },
      { en: 'Define softmax. You hand it a list of raw scores.', py: 'def softmax(logits):' },
      { en: 'Find the biggest score. We will subtract it from all of them, which changes no probabilities but stops exp from blowing up.', py: 'biggest = max(logits)', depth: 1 },
      { en: 'Turn every score into a positive number with exp (after subtracting the biggest).', py: 'exps = [math.exp(x - biggest) for x in logits]', depth: 1 },
      { en: 'Add them all up.', py: 'total = sum(exps)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'Now turn each positive number into a probability. What should we hand back?',
        options: [
          "Each number minus the total",
          "Each number divided by the total: its share of the whole",
          "Each number times the total",
          "Each number divided by the biggest number",
        ],
        answer: 1,
        why: { 0: 'Subtracting could make numbers negative again, and they would not add up to 1.', 2: 'That makes the numbers bigger, not shares of anything.', 3: 'That would make the biggest one exactly 1, but they would not add up to 1.' },
        en: 'Hand back each number divided by the total: its share of the whole.',
        py: 'return [e / total for e in exps]',
      },
      { en: 'Try it on three scores.', py: 'print(softmax([2.0, 1.0, 0.1]))' },
    ],
  },

  'ch8-signal': {
    lines: [
      { en: 'Define the error signal: how should the loss change if we nudge each score up?', py: 'def error_signal(logits, target):' },
      { en: 'First turn the scores into probabilities.', py: 'probs = softmax(logits)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'For each score, what is the error signal?',
        options: [
          'The probability the model gave it, minus 1 if it was the right answer (minus 0 otherwise)',
          'The probability the model gave it, plus 1 if it was the right answer',
          'Just the probability the model gave it',
          '1 minus the probability the model gave it',
        ],
        answer: 0,
        why: { 1: 'Adding would push the right answer\'s score down. It should go up, so its signal must be negative.', 2: 'That ignores which answer was actually right.', 3: 'This has the wrong sign for the wrong answers, and treats the right answer like the wrong ones.' },
        en: 'For each score: what the model predicted, minus what actually happened (1 for the right answer, 0 for the rest).',
        py: 'return [probs[i] - (1 if i == target else 0) for i in range(len(probs))]',
      },
      { en: 'Try it: three scores, and the correct answer is number 2.', py: 'print(error_signal([0.3, -1.2, 2.0], 2))' },
    ],
  },

  'ch9-dot': {
    lines: [
      { en: 'Define dot. You hand it two lists of numbers of the same length.', py: 'def dot(x, w):' },
      {
        blank: true, depth: 1,
        ask: 'How do we measure how much two lists "agree"?',
        options: [
          'Multiply each pair of matching numbers, then add up all the results',
          'Add each pair of matching numbers, then multiply the results',
          'Multiply every number from both lists together',
          'Add up every number from both lists',
        ],
        answer: 0,
        why: { 1: 'Close in spirit, but multiplying matching numbers first is what rewards "both are big" and punishes "one big, one opposite".', 2: 'That collapses everything into one product and ignores which numbers sit in the same position.', 3: 'That would ignore the pairing completely: the same answer however the lists lined up.' },
        en: 'Multiply each pair of matching numbers, then add up all the results.',
        py: 'return sum(xi * wi for xi, wi in zip(x, w))',
      },
      { en: 'Define linear. It takes a list of numbers x and a table w made of rows.', py: 'def linear(x, w):' },
      { en: 'Take the dot product of x with every row: one score per row.', py: 'return [dot(x, row) for row in w]', depth: 1 },
      { en: 'Try the dot product on two small lists. Expect 32.', py: 'print(dot([1, 2, 3], [4, 5, 6]))' },
      { en: 'Try a tiny linear layer. Expect [11.0, -1.5].', py: 'print(linear([1.0, 2.0], [[3.0, 4.0], [0.5, -1.0]]))' },
    ],
  },

  'ch9-embed': {
    lines: [
      { en: 'Borrow the toolkit for reading data files.', py: 'import json' },
      { en: 'Load the real trained dials of the model (after 3,000 steps of training).', py: "W = json.load(open('weights.json'))['checkpoints']['3000']" },
      { en: 'The token table: one row of 16 numbers for each of the 27 symbols.', py: "wte = W['wte']" },
      { en: 'The position table: one row of 16 numbers for each of the 8 positions.', py: "wpe = W['wpe']" },
      { en: 'Pick a symbol: number 0, the letter a.', py: 'token_id = 0' },
      { en: 'Pick a position: number 2, the third spot in a name.', py: 'pos_id = 2' },
      { en: "Look up the letter's row.", py: 'tok_emb = wte[token_id]' },
      { en: "Look up the position's row.", py: 'pos_emb = wpe[pos_id]' },
      {
        blank: true, depth: 0,
        ask: 'Combine the two rows into one list that says both WHICH letter and WHERE it sits. How?',
        options: ['Multiply the two numbers at each place', 'Add the two numbers at each place', 'Keep only the letter row', 'Subtract the position row from the letter row'],
        answer: 1,
        why: { 0: 'Multiplying would wipe out the letter wherever the position number happened to be near zero.', 2: 'Then the model would not know where in the name it is.', 3: 'It could work, but the model uses plain addition, which keeps the two signals easy to tell apart.' },
        en: 'Add the two rows together, number by number.',
        py: 'x = [t + p for t, p in zip(tok_emb, pos_emb)]',
      },
      { en: 'Show the first five numbers.', py: 'print([round(v, 3) for v in x[:5]])' },
    ],
  },

  'ch9-matrix': {
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: 'Define matrix: a table of nout rows and nin columns. std says how spread out the random numbers are.', py: 'def matrix(nout, nin, std=0.02):' },
      {
        blank: true, depth: 1,
        ask: 'What should every cell of the table hold at the start of training?',
        options: [
          'Always exactly 0',
          'A small random number: from a bell curve centred on 0 with spread std',
          'The number std itself, in every cell',
          'A random whole number between 0 and 100',
        ],
        answer: 1,
        why: { 0: 'If every dial starts equal, every dial gets the same slope and they stay twins forever. Randomness breaks the tie.', 2: 'Same problem as zero: all the dials identical.', 3: 'Far too big. The first guesses would be wild, and the loss enormous.' },
        en: 'Every cell holds a small random number from a bell curve centred on 0.',
        py: 'return [[random.gauss(0, std) for _ in range(nin)] for _ in range(nout)]',
      },
      { en: 'Make a 3 by 4 table.', py: 'm = matrix(3, 4)' },
      { en: 'Show its shape.', py: "print(len(m), 'rows of', len(m[0]), 'numbers')" },
      { en: 'Show the first row.', py: 'print([round(v, 3) for v in m[0]])' },
    ],
  },

  'ch10-attend': {
    lines: [
      { en: 'Define attend. It gets one query (the question) plus a list of keys (labels) and a list of values (contents), one of each per earlier position.', py: 'def attend(q, keys, values):' },
      { en: 'Remember how long the lists are (we need it for scaling).', py: 'd = len(q)', depth: 1 },
      { en: 'Step 1. For every earlier position, take the dot product of the query with its key (the match), and divide by the square root of d.', py: 'scores = [sum(qi * ki for qi, ki in zip(q, k)) / d ** 0.5 for k in keys]', depth: 1 },
      { en: 'Step 2. Turn the scores into weights that add up to 1.', py: 'weights = softmax(scores)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'Step 3. How do we turn the weights into one answer?',
        options: [
          'Blend the values: for each place j, add up (weight × value[j]) over all earlier positions',
          'Pick the value with the biggest weight and ignore the rest',
          'Add the weights up',
          'Multiply all the values together',
        ],
        answer: 0,
        why: { 1: 'That would be a hard choice. Attention is a soft one: everyone contributes in proportion to their weight, which also keeps the slopes flowing back to every position.', 2: 'The weights add to 1 by construction, so that tells us nothing.', 3: 'The weights would play no part.' },
        en: 'Blend the values: each position contributes its value, scaled by its weight.',
        py: 'return [sum(w * v[j] for w, v in zip(weights, values)) for j in range(len(values[0]))]',
      },
      { en: 'Try it: a question that matches the first label.', py: 'print(attend([1.0, 0.0], [[1.0, 0.0], [0.0, 1.0]], [[10.0, 0.0], [0.0, 10.0]]))' },
    ],
  },

  'ch11-heads': {
    lines: [
      { en: 'Pretend this is a query: 16 numbers.', py: 'q = [round(0.1 * i, 1) for i in range(16)]' },
      { en: 'We will use 4 heads.', py: 'n_head = 4' },
      { en: 'Each head gets an equal chunk: 16 divided by 4 = 4 numbers. (The double slash divides and drops any remainder.)', py: 'head_dim = len(q) // n_head' },
      { en: 'Start an empty list to hold each head\'s chunk.', py: 'heads = []' },
      { en: 'For each head, in turn...', py: 'for h in range(n_head):' },
      { en: '...work out where its chunk starts: head 0 at 0, head 1 at 4, head 2 at 8, and so on.', py: 'hs = h * head_dim', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'Which part of q belongs to this head?',
        options: [
          'Just the single number at position hs',
          'The slice of q from position hs up to (not including) hs + head_dim',
          'The whole of q',
          'The last head_dim numbers of q',
        ],
        answer: 1,
        why: { 0: 'A head needs a chunk of head_dim numbers, not one.', 2: 'Then every head would see the same thing, and splitting would achieve nothing.', 3: 'Then every head would get the same last chunk instead of its own.' },
        en: 'Take the slice of q from hs up to hs + head_dim.',
        py: 'chunk = q[hs:hs + head_dim]',
      },
      { en: 'Keep the chunk.', py: 'heads.append(chunk)', depth: 1 },
      { en: 'Now glue the four chunks back into one list (this is what the model does with the four heads\' answers).', py: 'x_attn = []' },
      { en: 'For each head\'s part...', py: 'for part in heads:' },
      { en: '...add its numbers to the end of the long list.', py: 'x_attn.extend(part)', depth: 1 },
      { en: 'Show head 1\'s chunk.', py: 'print(heads[1])' },
      { en: 'Did gluing the chunks reproduce the original list?', py: 'print(x_attn == q)' },
    ],
  },

  'ch12-mlp': {
    lines: [
      { en: 'Define relu: a one-way gate for a single number.', py: 'def relu(v):' },
      {
        blank: true, depth: 1,
        ask: 'What should the gate do with a number v?',
        options: [
          'Let positive numbers through unchanged, and turn negative numbers into 0',
          'Turn every number into 0',
          'Turn every number into its absolute value',
          'Square the number',
        ],
        answer: 0,
        why: { 1: 'Then nothing would ever get through, and the layer after it would see only zeros.', 2: 'That keeps negatives alive, as positives. A gate is meant to block them.', 3: 'Squaring is a different step (the real model does it AFTER the gate). The gate itself blocks the negatives.' },
        en: 'Let positive numbers through, and block negative ones (turn them into 0).',
        py: 'return max(0, v)',
      },
      { en: 'Define the MLP block. You hand it a list x and two tables of dials, fc1 and fc2.', py: 'def mlp(x, fc1, fc2):' },
      { en: 'Expand: a linear layer turns the short list into a longer one.', py: 'h = linear(x, fc1)', depth: 1 },
      { en: 'Gate every number with relu, then square it (that is what microgpt does).', py: 'h = [relu(v) ** 2 for v in h]', depth: 1 },
      { en: 'Shrink: a second linear layer turns the long list back into a short one.', py: 'return linear(h, fc2)', depth: 1 },
      { en: 'Try it on a tiny example. Expect [2.0, 0.5].', py: 'print(mlp([1.0, -2.0], [[1, 0], [0, 1], [1, 1]], [[2, 3, 4], [0.5, 0.5, 0.5]]))' },
    ],
  },

  'ch13-rmsnorm': {
    lines: [
      { en: 'Define rmsnorm. You hand it a list of numbers.', py: 'def rmsnorm(x):' },
      { en: 'Square every number and take the average: how loud the list is, overall.', py: 'ms = sum(xi * xi for xi in x) / len(x)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'What number should we multiply every item by, to bring the list to a standard volume?',
        options: [
          'The average itself',
          '1 divided by the square root of (the average + a tiny safety amount)',
          'The square root of the average',
          '1 minus the average',
        ],
        answer: 1,
        why: { 0: 'A loud list would then be made even louder.', 2: 'That multiplies loud lists by a big number, making them louder. We want to divide by the volume.', 3: 'That has no connection to volume: a list with average 5 would get a negative scale.' },
        en: 'One divided by the square root of the average, plus a tiny safety amount so we never divide by zero.',
        py: 'scale = (ms + 1e-5) ** -0.5',
      },
      { en: 'Multiply every number by the scale.', py: 'return [xi * scale for xi in x]', depth: 1 },
      { en: 'Try it on the list 3, -4.', py: 'print(rmsnorm([3.0, -4.0]))' },
    ],
  },

  'ch13-residual': {
    lines: [
      { en: 'Define block: it wraps any layer in a skip lane.', py: 'def block(x, layer):' },
      { en: 'Remember where we started.', py: 'x_residual = x', depth: 1 },
      { en: 'Let the layer propose something.', py: 'x = layer(x)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'How do we combine what the layer produced with what we started with?',
        options: [
          'Throw away what we started with, and keep only the layer\'s output',
          'Add the two together, number by number: the layer\'s output becomes an EDIT to what was there',
          'Multiply the two together, number by number',
          'Keep only what we started with',
        ],
        answer: 1,
        why: { 0: 'That is a plain stack with no skip lane, where everything must pass through every layer and can fade away.', 2: 'Multiplying could wipe out the original wherever the layer\'s output happened to be near zero.', 3: 'Then the layer would have no effect at all.' },
        en: 'Add the two together, number by number: the layer proposes an edit, and we apply it.',
        py: 'return [a + b for a, b in zip(x, x_residual)]',
      },
      { en: 'A layer that adds 10 and 20. Expect [11.0, 22.0].', py: 'print(block([1.0, 2.0], lambda v: [10.0, 20.0]))' },
      { en: 'A layer that does nothing leaves the lane untouched. Expect [1.0, 2.0].', py: 'print(block([1.0, 2.0], lambda v: [0.0, 0.0]))' },
    ],
  },

  'ch14-gpt': {
    intro: 'This is the whole model. The helper recipes from earlier chapters (linear, softmax, rmsnorm) and the trained dials W are already loaded. Two steps are missing, both the same kind.',
    lines: [
      { en: 'The model: it reads ONE symbol (at a given position) and returns 27 scores for what comes next. keys and values are the filing cabinet of earlier positions.', py: 'def gpt(token_id, pos_id, keys, values):' },
      { en: 'Look up the letter and the position, and add the two lists (Chapter 9).', py: "x = [t + p for t, p in zip(W['wte'][token_id], W['wpe'][pos_id])]", depth: 1 },
      { en: 'Normalise it (Chapter 13).', py: 'x = rmsnorm(x)', depth: 1 },
      { en: 'ATTENTION BLOCK. Remember where the lane is now.', py: 'x_residual = x', depth: 1 },
      { en: 'Normalise the copy that goes into the block.', py: 'x = rmsnorm(x)', depth: 1 },
      { en: 'Make the query, key and value lists with three linear layers (Chapter 10).', py: "q = linear(x, W['layer0.attn_wq'])", depth: 1 },
      { en: 'Same for the key...', py: "k = linear(x, W['layer0.attn_wk'])", depth: 1 },
      { en: '...and the value.', py: "v = linear(x, W['layer0.attn_wv'])", depth: 1 },
      { en: 'File this position\'s key and value in the cabinet.', py: 'keys.append(k)', depth: 1 },
      { en: '...and the value.', py: 'values.append(v)', depth: 1 },
      { en: 'Start an empty list for the heads\' answers.', py: 'x_attn = []', depth: 1 },
      { en: 'For each head (Chapter 11)...', py: 'for h in range(n_head):', depth: 1 },
      { en: '...find its chunk, and slice out its part of the query, and of every filed key and value.', py: 'hs = h * head_dim', depth: 2 },
      { en: 'This head\'s part of the query...', py: 'q_h = q[hs:hs + head_dim]', depth: 2 },
      { en: '...of every filed key...', py: 'k_h = [ki[hs:hs + head_dim] for ki in keys]', depth: 2 },
      { en: '...and of every filed value.', py: 'v_h = [vi[hs:hs + head_dim] for vi in values]', depth: 2 },
      { en: 'Score each earlier position: dot product with the query, scaled by the square root of the chunk size.', py: 'scores = [sum(q_h[j] * k_h[t][j] for j in range(head_dim)) / head_dim ** 0.5 for t in range(len(k_h))]', depth: 2 },
      { en: 'Softmax the scores into weights.', py: 'weights = softmax(scores)', depth: 2 },
      { en: 'Blend the values by those weights, and add the head\'s answer to the list.', py: 'x_attn.extend([sum(weights[t] * v_h[t][j] for t in range(len(v_h))) for j in range(head_dim)])', depth: 2 },
      { en: 'Mix the four answers with one more linear layer.', py: "x = linear(x_attn, W['layer0.attn_wo'])", depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'Back on the lane: how does the attention block\'s answer rejoin what was already there?',
        options: ['Replace the lane with the block\'s answer', 'Add the block\'s answer to the lane, number by number (a skip lane)', 'Multiply them, number by number', 'Ignore the block\'s answer'],
        answer: 1,
        why: { 0: 'That is a plain stack. The lane would lose everything it carried (Chapter 13).', 2: 'Multiplying could wipe the lane out wherever the block\'s answer was near zero.', 3: 'Then attention would have no effect at all.' },
        en: 'Add the block\'s answer to the lane, number by number.',
        py: 'x = [a + b for a, b in zip(x, x_residual)]',
      },
      { en: 'MLP BLOCK. Remember where the lane is now.', py: 'x_residual = x', depth: 1 },
      { en: 'Normalise the copy going in.', py: 'x = rmsnorm(x)', depth: 1 },
      { en: 'Expand 16 numbers to 64 (Chapter 12).', py: "x = linear(x, W['layer0.mlp_fc1'])", depth: 1 },
      { en: 'Gate them with ReLU and square.', py: 'x = [max(0, v) ** 2 for v in x]', depth: 1 },
      { en: 'Shrink back to 16.', py: "x = linear(x, W['layer0.mlp_fc2'])", depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'The same question again, for the MLP block: how does its answer rejoin the lane?',
        options: ['Replace the lane with the block\'s answer', 'Add the block\'s answer to the lane, number by number', 'Multiply them, number by number', 'Ignore the block\'s answer'],
        answer: 1,
        why: { 0: 'The lane would lose everything it carried.', 2: 'Multiplying could wipe the lane out.', 3: 'Then the MLP would have no effect.' },
        en: 'Add the block\'s answer to the lane, number by number.',
        py: 'x = [a + b for a, b in zip(x, x_residual)]',
      },
      { en: 'Finally turn the 16 numbers into 27 scores, one per possible next symbol (Chapter 9).', py: "return linear(x, W['lm_head'])", depth: 1 },
      { en: 'A helper that feeds a name into the model one symbol at a time and returns probabilities for what comes next.', py: 'def next_probs(prefix):' },
      { en: 'Start with BOS, then the letters typed so far.', py: "ids = [BOS] + [cfg['uchars'].index(c) for c in prefix]", depth: 1 },
      { en: 'An empty filing cabinet.', py: 'keys, values = [], []', depth: 1 },
      { en: 'Read the symbols one at a time. Each call files its key and value for the next ones to look at.', py: 'for pos, t in enumerate(ids):', depth: 1 },
      { en: 'Run the model on this symbol.', py: 'logits = gpt(t, pos, keys, values)', depth: 2 },
      { en: 'Softmax the last scores into probabilities.', py: 'return softmax(logits)', depth: 1 },
      { en: 'Ask the model: what comes after "ka"?', py: "probs = next_probs('ka')" },
      { en: 'Show the three most likely next symbols.', py: 'top = sorted(range(len(probs)), key=lambda i: -probs[i])[:3]' },
      { en: 'Print them with their probabilities.', py: "print([(cfg['uchars'][i] if i < 26 else 'end', round(probs[i], 2)) for i in top])" },
    ],
  },

  'ch15-adam': {
    lines: [
      { en: 'Define one Adam step for ONE dial. It gets the dial\'s value p, its slope, its two running averages m and v, and t (which step this is, counting from 1).', py: 'def adam_step(p, grad, m, v, t, lr=0.01, beta1=0.9, beta2=0.95, eps=1e-8):' },
      {
        blank: true, depth: 1,
        ask: 'Momentum: how should the running average m of the slope be updated?',
        options: [
          'Throw the old m away and use the new slope',
          'Keep beta1 (90%) of the old m, and mix in the remaining 10% of the new slope',
          'Add the new slope to the old m',
          'Multiply the old m by the new slope',
        ],
        answer: 1,
        why: { 0: 'Then there is no memory at all, and the slope\'s noise goes straight through.', 2: 'Adding forever would let m grow without limit instead of tracking a typical slope.', 3: 'Multiplying has nothing to do with averaging.' },
        en: 'Keep 90% of the old average and mix in 10% of the new slope.',
        py: 'm = beta1 * m + (1 - beta1) * grad',
      },
      { en: 'The same recipe for the squared slope: v tracks how BIG this dial\'s slopes typically are.', py: 'v = beta2 * v + (1 - beta2) * grad ** 2', depth: 1 },
      { en: 'Start-up correction for m (the average starts at 0, so early values are too small).', py: 'm_hat = m / (1 - beta1 ** t)', depth: 1 },
      { en: 'Start-up correction for v.', py: 'v_hat = v / (1 - beta2 ** t)', depth: 1 },
      {
        blank: true, depth: 1,
        ask: 'The update. How far, and which way, should the dial move?',
        options: [
          'Subtract lr × m_hat, with no further scaling',
          'Subtract lr × m_hat ÷ (the square root of v_hat, plus a tiny eps): a step against the smoothed slope, scaled by how big this dial\'s slopes typically are',
          'Add lr × m_hat ÷ (the square root of v_hat)',
          'Subtract lr × v_hat',
        ],
        answer: 1,
        why: { 0: 'That is plain momentum. A steep dial would still take a far bigger step than a shallow one.', 2: 'Adding moves uphill: we want to go against the slope.', 3: 'v_hat is a squared size, not a direction. It would also always be positive.' },
        en: 'Subtract lr × m_hat ÷ (√v_hat + eps).',
        py: 'p = p - lr * m_hat / (v_hat ** 0.5 + eps)',
      },
      { en: 'Hand back the new value and the updated averages.', py: 'return p, m, v', depth: 1 },
    ],
  },

  'ch15-race': {
    intro: 'Nothing to fill in. Run Adam, with the step function you just wrote, on the valley from the page.',
    lines: [
      { en: 'The steep dial is 1000 times steeper than the other.', py: 'B = 1000' },
      { en: 'Start position.', py: 'x, y = -3.0, 1.2' },
      { en: 'Each dial keeps its own running averages, starting at 0.', py: 'mx = my = vx = vy = 0.0' },
      { en: 'Take up to 3,000 steps.', py: 'for t in range(1, 3001):' },
      { en: 'The slope of each dial.', py: 'gx, gy = x, B * y', depth: 1 },
      { en: 'Adam step for dial x...', py: 'x, mx, vx = adam_step(x, gx, mx, vx, t, lr=0.1)', depth: 1 },
      { en: '...and for dial y.', py: 'y, my, vy = adam_step(y, gy, my, vy, t, lr=0.1)', depth: 1 },
      { en: 'Stop when the loss is below 0.001.', py: 'if 0.5 * (x * x + B * y * y) < 0.001:', depth: 1 },
      { en: 'Say how many steps it took.', py: "print('Adam solved it in', t, 'steps')", depth: 2 },
      { en: 'And stop.', py: 'break', depth: 2 },
    ],
  },

  'ch16-loss': {
    intro: 'This recipe scores a whole name with the real trained model. It is the heart of the training loop (lines 155-169 of microgpt.py).',
    lines: [
      { en: 'Define name_loss. You hand it a name.', py: 'def name_loss(name):' },
      { en: 'Wrap the name in start/end symbols and turn it into numbers (Chapter 1).', py: "tokens = [BOS] + [uchars.index(ch) for ch in name] + [BOS]", depth: 1 },
      { en: 'The number of lessons: one per position, but at most block_size (8).', py: 'n = min(block_size, len(tokens) - 1)', depth: 1 },
      { en: 'An empty filing cabinet for keys and values (Chapter 10).', py: 'keys, values = [], []', depth: 1 },
      { en: 'An empty list to collect each lesson\'s loss.', py: 'losses = []', depth: 1 },
      { en: 'One lesson per position...', py: 'for pos_id in range(n):', depth: 1 },
      { en: '...the model is shown the true symbol here, and must predict the next one.', py: 'token_id, target_id = tokens[pos_id], tokens[pos_id + 1]', depth: 2 },
      { en: 'Run the model: 27 scores.', py: 'logits = gpt(token_id, pos_id, keys, values)', depth: 2 },
      { en: 'Turn them into probabilities (Chapter 8).', py: 'probs = softmax(logits)', depth: 2 },
      {
        blank: true, depth: 2,
        ask: 'How surprised was the model by the symbol that really came next?',
        options: [
          'Minus the log of the probability the model gave to the right symbol',
          'The probability the model gave to the right symbol',
          'The log of the probability (no minus sign)',
          '1 minus the probability',
        ],
        answer: 0,
        why: { 1: 'That is a good-looking number but not the surprise: tiny probabilities would barely register (Chapter 3).', 2: 'Without the minus sign the score is negative, and "bigger is worse" is backwards.', 3: 'That does not turn products into sums, and it never gets huge for impossible predictions.' },
        en: 'Minus the log of the probability the model gave to the right symbol (Chapter 3).',
        py: 'loss_t = -math.log(probs[target_id])',
      },
      { en: 'Keep this lesson\'s loss.', py: 'losses.append(loss_t)', depth: 2 },
      { en: 'The name\'s loss is the average over its lessons.', py: 'return sum(losses) / n', depth: 1 },
      { en: 'Score "emma" with the trained model. Expect 2.548.', py: "print(round(name_loss('emma'), 3))" },
      { en: 'And "olivia".', py: "print(round(name_loss('olivia'), 3))" },
    ],
  },

  'ch17-generate': {
    lines: [
      { en: "Borrow Python's dice-rolling toolkit.", py: 'import random' },
      { en: 'Define generate: it writes one name using the trained model. A higher temperature means a more adventurous writer.', py: 'def generate(temperature=0.5):' },
      { en: 'An empty filing cabinet, and a start from the start symbol.', py: 'keys, values = [], []', depth: 1 },
      { en: 'Start from the start symbol.', py: 'token_id = BOS', depth: 1 },
      { en: 'The name begins empty.', py: "name = ''", depth: 1 },
      { en: 'At most 8 symbols (block_size)...', py: 'for pos_id in range(block_size):', depth: 1 },
      { en: '...ask the model for its 27 scores given the symbol just written.', py: 'logits = gpt(token_id, pos_id, keys, values)', depth: 2 },
      {
        blank: true, depth: 2,
        ask: 'Where does temperature go? How should it change the scores before softmax?',
        options: [
          'Divide every score by the temperature, then softmax',
          'Multiply every score by the temperature, then softmax',
          'Add the temperature to every score, then softmax',
          'Apply it after softmax, to the probabilities',
        ],
        answer: 0,
        why: { 1: 'That is backwards: a LOW temperature would then shrink the gaps and flatten the probabilities, but low temperature is meant to sharpen them.', 2: 'Adding the same number to every score changes nothing (Chapter 8: only the gaps matter).', 3: 'It has to act on the scores, so that softmax can turn the changed gaps into new probabilities.' },
        en: 'Divide every score by the temperature, then softmax. A small temperature stretches the gaps; a big one squeezes them.',
        py: 'probs = softmax([l / temperature for l in logits])',
      },
      { en: 'Spin the weighted wheel (Chapter 2) to pick the next symbol.', py: 'token_id = random.choices(range(len(probs)), weights=probs)[0]', depth: 2 },
      { en: 'If the wheel landed on the start/end symbol, the name is finished.', py: 'if token_id == BOS:', depth: 2 },
      { en: '...so stop.', py: 'break', depth: 3 },
      { en: 'Otherwise write the letter.', py: 'name += uchars[token_id]', depth: 2 },
      { en: 'Hand back the name.', py: 'return name', depth: 1 },
      { en: 'Fix the dice so the result is repeatable, then write 8 names.', py: 'random.seed(1)' },
      { en: 'Show them.', py: 'print([generate() for _ in range(8)])' },
    ],
  },
};
