import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 10, 'plain');
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page); await cont(page);
for (const [i, v] of [[0, '-2'], [1, '2'], [0, '2.5'], [1, '-1']]) await slide(page.locator(`input[aria-label="Query, ${['first','second'][i]} number"]`), v);
await shot(page, 'ch10-lookup');
console.log('lookup:', (await page.locator('.res').innerText()).replace(/\n/g, ' ').slice(-60));
await cont(page); await cont(page);
for (const v of ['1', '3', '5']) await slide(page.locator('input[aria-label="Length of the lists"]'), v);
await shot(page, 'ch10-scale');
console.log('scale:', (await page.locator('.foot').first().innerText()).slice(0, 120));
await cont(page); await cont(page);
const c = page.locator('.widget.cell').first();
await c.locator('.po:has-text("Blend the values")').click();
await c.locator('.recipe .bar button.btn.primary').click();
await c.locator('.oktxt').waitFor({ timeout: 90000 });
console.log('attend:', (await c.locator('.out').innerText()).trim().split('\n')[0]);
await cont(page);
await page.locator('select[aria-label="Training step"]').selectOption({ index: 0 });
await page.locator('select[aria-label="Attention head"]').selectOption('1');
await page.locator('select[aria-label="Training step"]').selectOption({ index: 4 });
await page.locator('input[aria-label="Name to read"]').fill('mariah');
await page.waitForTimeout(400);
await shot(page, 'ch10-real');
console.log('pred:', (await page.locator('.pred').innerText()).replace(/\n/g, ' '));
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH10 OK');
