import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 11, 'plain');

await cont(page);
await page.locator('.opt:has-text("No: splitting costs no extra dials")').click();
await cont(page);
const c = page.locator('.widget.cell').first();
await c.locator('.po:has-text("The slice of q from position hs")').click();
await c.locator('.recipe .bar button.btn.primary').click();
await c.locator('.oktxt').waitFor({ timeout: 90000 });
console.log('heads:', (await c.locator('.out').innerText()).trim().split('\n').slice(0, 2).join(' | '));
await cont(page);
await page.locator('input[aria-label="Name to read"]').fill('mariah');
await page.locator('select[aria-label="Training step"]').selectOption({ index: 0 });
await page.locator('select[aria-label="Training step"]').selectOption({ index: 4 });
await page.locator('.am rect').nth(5).click();
await page.waitForTimeout(500);
await shot(page, 'ch11-allheads');
await cont(page); await cont(page);
for (const i of [0, 1, 2, 3]) await page.locator('.tg').nth(i % 4).click();
await page.locator('.tg').nth(0).click();
await page.waitForTimeout(300);
await shot(page, 'ch11-switch');
console.log('switch:', (await page.locator('.big').innerText()).replace(/\n+/g, ' '));
console.log('per-head:', (await page.locator('.row .v').allInnerTexts()).join(' '));
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH11 OK');
