import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 12, 'plain');

await cont(page);
await page.locator('.opt:has-text("Just 1 layer")').click();
await cont(page);
for (let i = 0; i < 4; i++) await page.locator('button:has-text("Train 100 steps")').click();
console.log('none:', (await page.locator('.stats').innerText()).replace(/\n+/g, ' '));
await page.locator('.chip:has-text("Hidden layer + ReLU")').click();
await page.locator('button:has-text("Train to 3,000")').click();
await page.waitForFunction(() => document.querySelector('.stats')?.innerText.includes('3000'), null, { timeout: 30000 });
await page.waitForTimeout(300);
await shot(page, 'ch12-xor');
console.log('relu:', (await page.locator('.stats').innerText()).replace(/\n+/g, ' '));
await cont(page); await cont(page);
const c = page.locator('.widget.cell').first();
await c.locator('.po:has-text("Let positive numbers through unchanged")').click();
await c.locator('.recipe .bar button.btn.primary').click();
await c.locator('.oktxt').waitFor({ timeout: 90000 });
console.log('mlp:', (await c.locator('.out').innerText()).trim().split('\n')[0]);
await cont(page);
await page.locator('input[aria-label="Name to read"]').fill('kayla');
await page.locator('.pb').nth(2).click();
await shot(page, 'ch12-neurons');
console.log('neurons:', (await page.locator('.sum').innerText()).slice(0, 80));
await cont(page); await cont(page);
await page.locator('.tg').nth(0).click(); await page.locator('.tg').nth(1).click(); await page.locator('.tg').nth(0).click();
await page.waitForTimeout(300);
await shot(page, 'ch12-blocks');
console.log('rows:', (await page.locator('.row .v').allInnerTexts()).join(' '));
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH12 OK');
