import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 13, 'plain');
const cell = (n) => page.locator('.widget.cell').nth(n);
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page);
await page.locator('.opt:has-text("It vanishes")').click();
await cont(page);
console.log('plain:', (await page.locator('.widget:has-text("Deep stacks") .verdict').innerText()).slice(0, 70));
await page.locator('.chip:has-text("+ skip lane")').click();
console.log('skip:', (await page.locator('.widget:has-text("Deep stacks") .verdict').innerText()).slice(0, 70));
await page.locator('.chip:has-text("Both")').click();
await page.locator('select[aria-label="Starting dial size"]').selectOption('0.2');
await page.waitForTimeout(300);
await shot(page, 'ch13-deep');
console.log('both big:', (await page.locator('.widget:has-text("Deep stacks") .verdict').innerText()).slice(0, 80));
await page.locator('.chip:has-text("A plain stack")').click();
console.log('plain big:', (await page.locator('.widget:has-text("Deep stacks") .verdict').innerText()).slice(0, 70));
await cont(page); await cont(page);
await cell(0).locator('.po:has-text("Add the two together")').click();
await cell(0).locator('.recipe .bar button.btn.primary').click();
await cell(0).locator('.oktxt').waitFor({ timeout: 90000 });
await cont(page);
for (const v of ['1', '2', '4']) await slide(page.locator('input#st'), v);
await page.waitForTimeout(300);
await shot(page, 'ch13-stream');
console.log('stream:', (await page.locator('.rows').innerText()).replace(/\n+/g, ' '));
await cont(page); await cont(page);
for (const [i, v] of [[0, '3'], [1, '-2'], [2, '1'], [3, '4']]) await slide(page.locator(`input[aria-label="Number ${i + 1}"]`), v);
await slide(page.locator('input[aria-label="Volume"]'), '9');
await shot(page, 'ch13-norm');
await cont(page);
await cell(1).locator('.po:has-text("One divided by the square root")').click().catch(async () => { await cell(1).locator('.po:has-text("1 divided by the square root")').click(); });
await cell(1).locator('.recipe .bar button.btn.primary').click();
await cell(1).locator('.oktxt').waitFor({ timeout: 90000 });
console.log('rmsnorm:', (await cell(1).locator('.out').innerText()).trim().split('\n')[0]);
await cont(page); await shot(page, 'ch13-diagram'); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH13 OK');
