import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 14, 'plain');

await cont(page); await cont(page);
await page.locator('input[type=number]:not([disabled])').first().fill('3072');
await page.locator('button:has-text("Lock in guess")').click();
await page.locator('button.chip:has-text("GPT-2-small-sized")').click();
console.log('gpt2-ish:', (await page.locator('.tot').innerText()).replace(/\n/g, ' '));
await page.locator('button.chip:has-text("microgpt (the real file)")').click();
await shot(page, 'ch14-params');
console.log('microgpt:', (await page.locator('.tot').innerText()).replace(/\n/g, ' '));
await cont(page); await cont(page);
await page.locator('input[aria-label="Name to read"]').fill('mariah');
await page.locator('.pb').nth(3).click();
await page.waitForTimeout(400);
await shot(page, 'ch14-xray');
console.log('xray top:', (await page.locator('.out').innerText()).replace(/\n+/g, ' ').slice(0, 140));
await cont(page);
const c = page.locator('.widget.cell').first();
await c.locator('.po:has-text("Add the block")').first().click();
await c.locator('.po:has-text("Add the block")').first().click();
await c.locator('.recipe .bar button.btn.primary').click();
await c.locator('.oktxt').waitFor({ timeout: 120000 });
console.log('gpt:', (await c.locator('.out').innerText()).trim().split('\n').slice(0, 2).join(' | '));
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
await page.waitForTimeout(400);
console.log('file pill:', (await page.locator('.pill').nth(1).innerText()).replace(/\n/g, ' '));
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH14 OK');
