import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 15, 'plain');
const cell = (n) => page.locator('.widget.cell').nth(n);
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page);
await page.locator('.opt:has-text("steep dial steps about 1,000 times further")').click();
await cont(page);
for (const b of ['30', '1,000', '100,000']) await page.locator(`.chip:has-text("${b}×")`).click();
await page.waitForTimeout(300);
await shot(page, 'ch15-race');
console.log('race:', (await page.locator('.rows').innerText()).replace(/\n+/g, ' | '));
await cont(page); await cont(page);
await slide(page.locator('input[aria-label="Memory"]'), '0.5');
await page.locator('.chk input').check();
await page.locator('button:has-text("New noise")').click();
await shot(page, 'ch15-ema');
await cont(page);
for (const [i, v] of [[0, '3'], [1, '-3'], [0, '1']]) await slide(page.locator(`input[aria-label="Slope of dial ${['A','B'][i]} (power of ten)"]`), v);
console.log('stepscale:', (await page.locator('.t tbody').innerText()).replace(/\s+/g, ' '));
await cont(page);
await cell(0).locator('.po:has-text("Keep beta1 (90%)")').click();
await cell(0).locator('.po:has-text("Subtract lr × m_hat ÷")').click();
await cell(0).locator('.recipe .bar button.btn.primary').click();
await cell(0).locator('.oktxt').waitFor({ timeout: 90000 });
await cont(page);
await cell(1).locator('.recipe .bar button.btn.primary').click();
await cell(1).locator('.oktxt').waitFor({ timeout: 90000 });
console.log('race cell:', (await cell(1).locator('.out').innerText()).trim().split('\n').join(' | '));
await cont(page);
for (const v of ['100', '250', '400']) await slide(page.locator('input[aria-label="Training step"]'), v);
await shot(page, 'ch15-decay');
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH15 OK');
