import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 16, 'plain');

await cont(page);
await page.locator('input[aria-label="Name to read"]').fill('olivia');
await page.locator('select[aria-label="Training step"]').selectOption({ index: 0 });
await page.locator('select[aria-label="Training step"]').selectOption({ index: 4 });
await page.waitForTimeout(300);
await shot(page, 'ch16-lessons');
console.log('lessons total:', (await page.locator('.r.tot').innerText()).replace(/\n+/g, ' '));
await cont(page); await cont(page);
const c = page.locator('.widget.cell').first();
await c.locator('.po:has-text("Minus the log of the probability the model gave")').click();
await c.locator('.recipe .bar button.btn.primary').click();
await c.locator('.oktxt').waitFor({ timeout: 120000 });
console.log('name_loss:', (await c.locator('.out').innerText()).trim().split('\n').slice(0, 2).join(' | '));
await cont(page); await cont(page);
await page.locator('input[type=number]:not([disabled])').fill('2.7');
await page.locator('button:has-text("Lock in guess")').click();
await cont(page);
const t0 = Date.now();
await page.locator('button:has-text("Start training")').click();
await page.locator('.done').waitFor({ timeout: 900000 });
const secs = Math.round((Date.now() - t0) / 1000);
console.log('training 100 steps in the browser took', secs, 's');
await shot(page, 'ch16-train');
console.log('done:', (await page.locator('.done').innerText()).replace(/\n/g, ' ').slice(0, 160));
console.log('info:', (await page.locator('.info').innerText()).replace(/\s+/g, ' '));
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH16 OK');
