import { launch, BASE, SHOTS, cont, shot, solve, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 3);
const cells = () => page.locator('.widget.cell');
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page);
const nm = page.locator('input[maxlength="14"]');
await nm.fill('olivia'); await page.locator('.grp button:has-text("Letter frequencies")').click();
await shot(page, 'ch3-nameprob');
await page.locator('.grp button:has-text("Bigram table")').click();
await nm.fill('xqzvb');
await shot(page, 'ch3-impossible');
await cont(page); await cont(page);
await page.locator('.opt:has-text("alexandria")').click();
await cont(page); await cont(page);
for (const v of ['0.5', '2', '1', '3']) await slide(page.locator('.widget input[type=range]').first(), v);
await shot(page, 'ch3-logs');
await cont(page);
console.log('surprise:', await solve(page, cells().nth(0), `import math\ndef surprise(p):\n    return -math.log(p)\nfor p in [1, 0.5, 0.1, 1/27]:\n    print(p, round(surprise(p), 3))`));
await cont(page); await cont(page);
console.log('loss:', await solve(page, cells().nth(1), `def name_loss(name):\n    tokens = [BOS] + [uchars.index(ch) for ch in name] + [BOS]\n    losses = []\n    for prev, nxt in zip(tokens, tokens[1:]):\n        p = P(prev, nxt)\n        losses.append(-math.log(p))\n    return sum(losses) / len(losses)\nfor n in ['emma', 'olivia', 'mia']:\n    print(n, round(name_loss(n), 3))`));
await cont(page);
await page.locator('.grp button:has-text("never counted")').click();
await shot(page, 'ch3-heldout-inf');
const al = page.locator('input[aria-label="Smoothing"]');
await slide(al, '1');
await page.waitForTimeout(400);
await shot(page, 'ch3-heldout');
const board = await page.locator('.widget:has-text("scoreboard")').innerText();
console.log(board.replace(/\n+/g, ' | ').slice(0, 400));
await cont(page); await cont(page);
await cells().nth(2).locator('button:has-text("Run")').click();
await cells().nth(2).locator('.out').waitFor();
console.log('break:', (await cells().nth(2).locator('.out').innerText()).trim().split('\n').pop());
await cont(page);
await shot(page, 'ch3-ceiling');
await cont(page);
await page.locator('button:has-text("Light up")').click();
await page.waitForTimeout(700);
const pill = await page.locator('.pill').first().innerText();
console.log('best loss pill:', pill.replace(/\n/g, ' '));
await page.keyboard.press('Escape');
await page.locator('.pill').first().click();
await page.waitForTimeout(400);
await shot(page, 'ch3-museum');
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH3 OK');
