import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 5, 'plain');
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page);
await page.locator('.opt:has-text("Up")').first().click();
await cont(page);
await slide(page.locator('input[aria-label="Wiggle size (log)"]'), '-0.5');
await slide(page.locator('input[aria-label="Wiggle size (log)"]'), '-4');
await page.waitForTimeout(300);
await shot(page, 'ch5-wiggle');
console.log('wiggle readout:', (await page.locator('.eq').innerText()).replace(/\n/g, ' '));
await cont(page); await cont(page);
const map = page.locator('svg.map');
for (const [x, y] of [[100, 100], [220, 220], [90, 200], [200, 90]]) await map.click({ position: { x, y } });
await page.locator('label.tg input').check();
await shot(page, 'ch5-compass');
await cont(page);
for (let i = 0; i < 5; i++) await page.locator('button:has-text("Take one step")').click();
await shot(page, 'ch5-descent-ok');
console.log('descent:', (await page.locator('div.ok:has-text("Within 0.003")').innerText()).trim());
await page.locator('button:has-text("Start over")').click();
await slide(page.locator('input[type=range]').last(), '1.1');
await page.locator('button:has-text("Take one step")').click();   // lr 1.1 throws dial A out of range on the very first step
await page.locator('.warn').waitFor();
await shot(page, 'ch5-descent-broke');
await page.locator('button:has-text("Start over")').click();
await cont(page); await cont(page);
const c1 = page.locator('.widget.cell').nth(0);
await c1.locator('.po:has-text("divide that change by h")').click();
await c1.locator('.recipe .bar button.btn.primary').click();
await c1.locator('.oktxt').waitFor({ timeout: 90000 });
console.log('slope:', (await c1.locator('.out').innerText()).trim().split('\n').slice(0, 2).join(' | '));
await cont(page);
const c2 = page.locator('.widget.cell').nth(1);
await c2.locator('.po:has-text("Subtract")').click();
await c2.locator('.recipe .bar button.btn.primary').click();
await c2.locator('.oktxt').waitFor({ timeout: 90000 });
console.log('descent cell:', (await c2.locator('.oktxt').innerText()).trim());
await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH5 OK');
