import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 6, 'plain');
const walk = async () => { const b = page.locator('button:has-text("Next step")'); while (await b.isEnabled()) await b.click(); };
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page);
await page.locator('.opt:has-text("Any one of them")').click();
await cont(page);
const sl = page.locator('.sliders input[type=range]');
await slide(sl.nth(1), '1.2'); await slide(sl.nth(2), '0.2'); await slide(sl.nth(3), '0.3');
await shot(page, 'ch6-funnel');
console.log('funnel:', (await page.locator('.check').innerText()).replace(/\n+/g, ' | '));
await cont(page); await cont(page); await cont(page);
await page.locator('input[type=number]:not([disabled])').fill('40');
await page.locator('button:has-text("Lock in guess")').click();
await cont(page);
await walk();
await shot(page, 'ch6-graph-end');
console.log('graph table:', (await page.locator('.t tbody').innerText()).replace(/\s+/g, ' '));
await page.locator('.chip:has-text("One input used twice")').click();
await walk();
console.log('twice table:', (await page.locator('.t tbody').innerText()).replace(/\s+/g, ' '));
await page.locator('.chip:has-text("baby version")').click();
await walk();
console.log('log table:', (await page.locator('.t tbody').innerText()).replace(/\s+/g, ' '));
await shot(page, 'ch6-graph-log');
await cont(page); await cont(page);
const c1 = page.locator('.widget.cell').nth(0);
await c1.locator('.po:has-text("The same as the upstream slope")').click();
await c1.locator('.po:has-text("The other input, b")').click();
await c1.locator('.recipe .bar button.btn.primary').click();
await c1.locator('.oktxt').waitFor({ timeout: 90000 });
console.log('backward rules:', (await c1.locator('.out').innerText()).trim().split('\n')[0]);
await cont(page);
const c2 = page.locator('.widget.cell').nth(1);
await c2.locator('.recipe .bar button.btn.primary').click();
await c2.locator('.out:has-text("going backwards")').waitFor({ timeout: 90000 });
console.log('verify:', (await c2.locator('.out').innerText()).trim().replace(/\n/g, ' | '));
await cont(page);
await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH6 OK');
