import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 8, 'plain');
const cell = (n) => page.locator('.widget.cell').nth(n);
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);

await cont(page);
await page.locator('.opt:has-text("Raise e to its power")').click();
await cont(page);
for (const [i, v] of [[0, '3.5'], [1, '-2'], [2, '1'], [3, '4']]) await slide(page.locator(`input[aria-label="Score for ${['a','e','n','r'][i]}"]`), v);
await page.locator('button:has-text("Make them huge")').click();
await shot(page, 'ch8-softmax');
console.log('huge:', (await page.locator('.note').last().innerText()).replace(/\n/g, ' | ').slice(0, 220));
await cont(page); await cont(page);
await cell(0).locator('.po:has-text("divided by the total: its share")').click();
await cell(0).locator('.recipe .bar button.btn.primary').click();
await cell(0).locator('.oktxt').waitFor({ timeout: 90000 });
console.log('softmax:', (await cell(0).locator('.out').innerText()).trim().split('\n')[0]);
await cont(page);
await page.locator('input[type=number]:not([disabled])').fill('0.693');
await page.locator('button:has-text("Lock in guess")').click();
await cont(page);
await cell(1).locator('.po:has-text("minus 1 if it was the right answer")').click();
await cell(1).locator('.recipe .bar button.btn.primary').click();
await cell(1).locator('.oktxt').waitFor({ timeout: 90000 });
console.log('signal:', (await cell(1).locator('.out').innerText()).trim().split('\n')[0]);
await cont(page);
for (let i = 0; i < 9; i++) await page.locator('button:has-text("25 steps")').click();
await page.waitForTimeout(300);
await shot(page, 'ch8-neural');
console.log('nb stats:', (await page.locator('.stats').last().innerText()).replace(/\n+/g, ' '));
await cont(page); await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH8 OK');
