import { launch, BASE, SHOTS, cont, shot, freshChapter } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch({ height: 1000 });
await freshChapter(page, 9, 'plain');
const cell = (n) => page.locator('.widget.cell').nth(n);
const slide = (loc, v) => loc.evaluate((el, v) => { el.value = v; el.dispatchEvent(new Event('input', { bubbles: true })); }, v);
const dragBy = async (loc, dx, dy) => { await loc.scrollIntoViewIfNeeded(); const b = await loc.boundingBox(); const x = b.x + b.width / 2, y = b.y + b.height / 2; await page.mouse.move(x, y); await page.mouse.down(); await page.mouse.move(x + dx / 2, y + dy / 2); await page.mouse.move(x + dx, y + dy); await page.mouse.up(); };

await cont(page);
await page.locator('.opt:has-text("short list of numbers")').click();
await cont(page); await cont(page);
await dragBy(page.locator('circle.h').first(), -60, 40);
await dragBy(page.locator('circle.h').nth(1), 30, -50);
console.log('dot readout:', (await page.locator('.calc2').innerText()).replace(/\n/g, ' '));
await shot(page, 'ch9-dot');
await cont(page);
const wi = page.locator('input.wi');
await wi.nth(0).fill('0.9'); await wi.nth(4).fill('0.1'); await wi.nth(8).fill('0.2');
await shot(page, 'ch9-linear');
await cont(page);
await cell(0).locator('.po:has-text("Multiply each pair of matching numbers")').click();
await cell(0).locator('.recipe .bar button.btn.primary').click();
await cell(0).locator('.oktxt').waitFor({ timeout: 90000 });
await cont(page);
for (const v of ['2', '4']) await slide(page.locator('input#stp'), v);
await page.waitForTimeout(1200);
await shot(page, 'ch9-embedding');
console.log('emb stats:', (await page.locator('.stat').innerText()).replace(/\n/g, ' '));
await cont(page); await cont(page);
await cell(1).locator('.po:has-text("Add the two numbers")').click();
await cell(1).locator('.recipe .bar button.btn.primary').click();
await cell(1).locator('.oktxt').waitFor({ timeout: 90000 });
console.log('embed:', (await cell(1).locator('.out').innerText()).trim().split('\n')[0]);
await cont(page);
await cell(2).locator('.po:has-text("small random number")').click();
await cell(2).locator('.recipe .bar button.btn.primary').click();
await cell(2).locator('.oktxt').waitFor({ timeout: 90000 });
console.log('matrix:', (await cell(2).locator('.oktxt').innerText()).trim());
await cont(page); await cont(page);
await page.locator('button:has-text("Light up")').click();
console.log('problems:', problems);
assert.equal(problems.length, 0);
await browser.close();
console.log('CH9 OK');
