import { launch, BASE, SHOTS, shot } from './lib.mjs';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
mkdirSync(SHOTS, { recursive: true });
const { browser, page, problems } = await launch();
await page.goto(BASE);
await page.locator('a.pill.gl').click();
assert.ok(page.url().endsWith('#/glossary'));
await page.locator('.gl .e').first().waitFor();
const all = await page.locator('.gl .e').count();
await page.locator('.gl input').fill('softmax');
await page.waitForFunction(() => document.querySelectorAll('.gl .e').length < 10);
const n = await page.locator('.gl .e').count();
console.log('terms:', all, 'matching "softmax":', n);
assert.ok(all > 40 && n >= 1 && n < all);
await page.locator('.gl .e a').first().click();
await page.waitForFunction(() => location.hash.startsWith('#/ch/'));
await page.goto(BASE + '#/glossary'); await shot(page, 'glossary');
console.log('problems:', problems); assert.equal(problems.length, 0);
await browser.close(); console.log('GLOSSARY OK');
